export declare enum ActivityAction {
    CREATE_BOARD = "CREATE_BOARD",
    UPDATE_BOARD = "UPDATE_BOARD",
    CREATE_LIST = "CREATE_LIST",
    UPDATE_LIST = "UPDATE_LIST",
    CREATE_CARD = "CREATE_CARD",
    UPDATE_CARD = "UPDATE_CARD",
    MOVE_CARD = "MOVE_CARD",
    DELETE_CARD = "DELETE_CARD",
    ADD_MEMBER = "ADD_MEMBER",
    REMOVE_MEMBER = "REMOVE_MEMBER",
    ATTACHMENT_ADDED = "ATTACHMENT_ADDED",
    CHECKLIST_COMPLETED = "CHECKLIST_COMPLETED",
    COMMENT_ADDED = "COMMENT_ADDED"
}
