import { OnModuleInit } from '@nestjs/common';
import { Repository, DataSource } from 'typeorm';
import type { ConfigType } from '@nestjs/config';
import { Workspace, WorkspaceMember, User } from '../../database/entities';
import { CreateWorkspaceDto, UpdateWorkspaceDto, InviteMemberDto } from './dto';
import { UsersService } from '../users/users.service';
import { MailerService } from '../notifications/mailer.service';
import { NotificationsService } from '../notifications/notifications.service';
import { AppCacheService } from '../../common/cache';
import { appConfig } from '../../config';
export declare class WorkspacesService implements OnModuleInit {
    private readonly workspaceRepository;
    private readonly workspaceMemberRepository;
    private readonly userRepository;
    private readonly dataSource;
    private readonly usersService;
    private readonly mailerService;
    private readonly app;
    private readonly notificationsService;
    private readonly cacheService;
    private readonly logger;
    constructor(workspaceRepository: Repository<Workspace>, workspaceMemberRepository: Repository<WorkspaceMember>, userRepository: Repository<User>, dataSource: DataSource, usersService: UsersService, mailerService: MailerService, app: ConfigType<typeof appConfig>, notificationsService: NotificationsService, cacheService: AppCacheService);
    private invalidateWorkspaceLists;
    private getActiveMemberUserIds;
    onModuleInit(): Promise<void>;
    private generateSlug;
    private ensureUniqueSlug;
    create(createWorkspaceDto: CreateWorkspaceDto, userId: string): Promise<Workspace>;
    findAllByUser(userId: string): Promise<Workspace[]>;
    findAll(): Promise<Workspace[]>;
    findOne(id: string): Promise<Workspace>;
    update(id: string, updateWorkspaceDto: UpdateWorkspaceDto): Promise<Workspace>;
    remove(id: string, requesterId: string): Promise<void>;
    restore(id: string, requesterId: string): Promise<Workspace>;
    findDeletedOwnedByUser(userId: string): Promise<Workspace[]>;
    inviteMember(workspaceId: string, inviteMemberDto: InviteMemberDto, inviterId: string): Promise<WorkspaceMember>;
    acceptInvitation(workspaceId: string, token: string, userId: string): Promise<WorkspaceMember>;
    getMembers(workspaceId: string): Promise<WorkspaceMember[]>;
    removeMember(workspaceId: string, memberId: string, requesterId: string): Promise<void>;
    private findUserByEmail;
    private findExistingMember;
    private generateInviteToken;
    private generateInviteLink;
    private createInvitation;
    private sendInvitationEmail;
    private getRoleDisplayName;
}
